services:
  nemo_vpn_bot:
    build: .
    container_name: nemo_vpn_bot
    restart: always
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - nemo_vpn_db
      - nemo_vpn_redis
    networks:
      - nemo_net

  nemo_vpn_webhooks:
    build: .
    command: python webhooks.py
    container_name: nemo_vpn_webhooks
    restart: always
    env_file:
      - .env
    expose:
      - "8080"
    depends_on:
      - nemo_vpn_db
    networks:
      - nemo_net

  nemo_vpn_db:
    image: postgres:15-alpine
    container_name: nemo_vpn_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vpn_bot
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nemo_net

  nemo_vpn_redis:
    image: redis:7-alpine
    container_name: nemo_vpn_redis
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - nemo_net

  nemo_vpn_nginx:
    image: nginx:alpine
    container_name: nemo_vpn_nginx
    restart: always
    ports:
      # Возвращаем порт 8082, но слушаем только локальные запросы от системного Nginx
      - "127.0.0.1:8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nemo_vpn_bot
      - nemo_vpn_webhooks
    networks:
      - nemo_net

networks:
  nemo_net:
    driver: bridge

volumes:
  pgdata:
  redisdata: